feat: introducing tracks for sessions
fossasia/open-event-frontend pull request #4796
Opened 2020-08-18 18:13 UTC by maze-runnar

![Screenshot from 2020-08-18 23-41-44](https://user-images.githubusercontent.com/56407566/90549746-91810e00-e1ac-11ea-80a4-68578a2fa122.png)
![Screenshot from 2020-08-18 23-41-41](https://user-images.githubusercontent.com/56407566/90549753-934ad180-e1ac-11ea-8a44-9b10c971a870.png)
![Screenshot from 2020-08-18 23-41-33](https://user-images.githubusercontent.com/56407566/90549757-947bfe80-e1ac-11ea-94e8-49da9b3663d7.png)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-08-18 18:15 UTC, maze-runnar commented
@iamareebjamal please review.

2020-08-18 18:17 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-18 18:53 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-19 13:24 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-19 18:07 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i,'days').toISOString());
Codacy found an issue: ['moment' is not defined.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:07 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-19 18:08 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i,'days').toISOString());
Codacy found an issue: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:08 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    let difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
Codacy found an issue: ['difference' is never reassigned. Use 'const' instead.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:08 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    let arr = new Array();
Codacy found an issue: ['arr' is never reassigned. Use 'const' instead.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:08 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i,'days').toISOString());
Codacy found an issue: [A space is required after ','.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:12 UTC, maze-runnar commented
video of working - https://youtu.be/gdotFtocMjc

2020-08-19 18:20 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i, 'days').toISOString());
Codacy found an issue: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:20 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-19 18:20 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i, 'days').toISOString());
Codacy found an issue: ['moment' is not defined.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-19 18:48 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-19 18:48 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i, 'days').toISOString());
Codacy found an issue: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-20 08:01 UTC, mariobehling requested changes
Please implement the design more closely to the website generator. Do not use the track color for the entire area. Compare https://summit.fossasia.org/event/schedule.html

![Screenshot from 2020-08-20 10-00-12](https://user-images.githubusercontent.com/1583873/90732935-1c0c5f00-e2cc-11ea-9baf-94e86bde13ee.png)

2020-08-20 08:07 UTC, mariobehling commented
In the screenshots, I dont see if all details are present. Here is the list what should definitely be there:
* Session Title
* Track
* Type (workshop, talk etc.)
* Speaker Name and links
* Time and Date
* Room
* Description

2020-08-20 08:26 UTC, maze-runnar commented
> In the screenshots, I dont see if all details are present. Here is the list what should definitely be there:
> 
> * Session Title
> * Track
> * Type (workshop, talk etc.)
> * Speaker Name and links
> * Time and Date
> * Room
> * Description

@mariobehling  I have updated the changes . please take a look - https://youtu.be/gdotFtocMjc,

2020-08-20 11:32 UTC, maze-runnar commented
@iamareebjamal @mariobehling  please take a look at these changes - 
![Screenshot from 2020-08-20 17-01-06](https://user-images.githubusercontent.com/56407566/90765009-de78f780-e306-11ea-87d0-45854cab2214.png)
![Screenshot from 2020-08-20 17-01-00](https://user-images.githubusercontent.com/56407566/90765018-e0db5180-e306-11ea-8f0d-9b8931250cb3.png)

2020-08-20 12:26 UTC, iamareebjamal commented
Don't show time in card. Try to mimick https://summit.fossasia.org/event/schedule.html as much as you can. Remove the outer card as well

Expanded session should show these details: https://github.com/fossasia/open-event-frontend/pull/4796#issuecomment-677447189

Not in the old UI. New UI is set to replace the old UI. So all the information should be available in the new UI itself including the date switcher as well

2020-08-20 13:20 UTC, maze-runnar commented
@iamareebjamal i have made it similar to https://summit.fossasia.org/event/schedule.html .
![Screenshot from 2020-08-20 18-48-50](https://user-images.githubusercontent.com/56407566/90775091-06238c00-e316-11ea-8f95-d72f4a0a43b0.png)

![Screenshot from 2020-08-20 18-48-41](https://user-images.githubusercontent.com/56407566/90775042-f441e900-e315-11ea-9050-d5f2822e1498.png)

2020-08-20 13:21 UTC, maze-runnar commented
![Screenshot from 2020-08-20 18-48-50](https://user-images.githubusercontent.com/56407566/90775144-1c314c80-e316-11ea-86d7-e18158e88190.png)

2020-08-20 13:31 UTC, iamareebjamal commented
Looks good. Please remove the time from card, only session box should be in a card. I'll review the implementation soon

2020-08-20 13:33 UTC, maze-runnar commented
> Looks good. Please remove the time from card, only session box should be in a card. I'll review the implementation soon

ok

2020-08-20 13:34 UTC, iamareebjamal commented
Also, use `isLight` utility function to change the text color in the card

2020-08-20 13:35 UTC, maze-runnar commented
> Also, use `isLight` utility function to change the text color in the card

which color?

2020-08-20 14:00 UTC, maze-runnar commented
@iamareebjamal please take a look -
![Screenshot from 2020-08-20 19-29-19](https://user-images.githubusercontent.com/56407566/90779456-7b459000-e31b-11ea-936a-56c71d181a83.png)
![Screenshot from 2020-08-20 19-29-16](https://user-images.githubusercontent.com/56407566/90779463-7da7ea00-e31b-11ea-9dcf-f7451a1a8bd5.png)

2020-08-20 14:10 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- app/controllers/public/sessions/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570&bid=19774994)

2020-08-20 14:10 UTC, niranjan94 commented on app/controllers/public/sessions/list.js
> +    	arr.push(moment(this.model.event.startsAt).add(i, 'days').toISOString());
Codacy found an issue: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6034570)

2020-08-20 14:25 UTC, iamareebjamal commented
Session Title and subtitle should be of same color. And there is still card nesting. The color card is sitting inside a white card

2020-08-20 14:51 UTC, maze-runnar commented
> Session Title and subtitle should be of the same color. And there is still card nesting. The color card is sitting inside a white card

No there is no card nesting, this is default accordion.

2020-08-20 14:54 UTC, maze-runnar commented
> Session Title and subtitle 

they should be white ?

2020-08-20 18:20 UTC, iamareebjamal commented
Yes

2020-08-20 19:04 UTC, mariobehling commented
I think the implementation here is more closely related to this issue https://github.com/fossasia/open-event-frontend/issues/4807

It seems you are implementing the tracks view page.

What is the difference between the different schedule pages? 
1. Schedule Page in calendar view (in future different view should be switchable)
1.a) Tracks Page - all sessions are sorted in list view according to date, time and track
1.b) Rooms Page - all sessions are sorted in list view according to date, time and room
2. Session Page - this page shows all sessions in alphabetical order (including accepted and confirmed ones that are not yet scheduled)

2020-08-20 22:44 UTC, iamareebjamal commented
Great work @maze-runnar. I'm going to take your UI and logic to implement #4808 as it is high priority and to be fixed by tomorrow. And then later, we can use the same components to implement track and schedule view.

Thanks for doing the hard work for me

2020-10-16 18:54 UTC, iamareebjamal commented
UI changed now

2020-10-16 18:54 UTC, closed without merging