WIP: Seperate the admin/sales tab into 2 subtabs
fossasia/open-event-frontend pull request #5066
Opened 2020-09-14 08:27 UTC by maze-runnar

Fixes #4954 

![Screenshot from 2020-09-14 13-55-39](https://user-images.githubusercontent.com/56407566/93062065-0fdcad00-f692-11ea-95ac-7c32abc9055e.png)
![Screenshot from 2020-09-14 13-55-34](https://user-images.githubusercontent.com/56407566/93062076-123f0700-f692-11ea-92de-4f4e225d53bc.png)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-09-14 09:25 UTC, maze-runnar commented
once https://github.com/fossasia/open-event-frontend/pull/5049 will be merged then, I will add here the download option in invoice#

2020-09-14 11:49 UTC, maze-runnar commented
> Notify button (opening a pop-up with email options depending on state)
>  Resend Invoice button

is there a feature available on server for sending mail for invoice?

2020-09-14 11:57 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +        valuePath       : 'identifier',
Codacy found an issue: [Extra space after key 'valuePath'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 11:57 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

2020-09-14 11:57 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +        cellComponent   : 'ui-table/cell/admin/sales/cell-action'
Codacy found an issue: [Extra space after key 'cellComponent'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 11:57 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +        name            : 'Action',
Codacy found an issue: [Extra space after key 'name'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:06 UTC, maze-runnar commented
![Screenshot from 2020-09-14 17-36-08](https://user-images.githubusercontent.com/56407566/93083851-d7000080-f6b0-11ea-9a3c-a15daf26a430.png)

2020-09-14 12:07 UTC, iamareebjamal commented
Not right now. So, let's hide that column for now and merge the PR and when there is an API, we'll show the column again

2020-09-14 12:26 UTC, iamareebjamal commented on app/controllers/admin/sales/invoices.js
> -        cellComponent : 'ui-table/cell/admin/sales/cell-action'
Please comment it out since this is a part of current code.

2020-09-14 12:37 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//         name            : 'Action',
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//       {
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//         cellComponent   : 'ui-table/cell/admin/sales/cell-action'
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//         valuePath       : 'identifier',
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +      },
Codacy found an issue: [Unexpected trailing comma.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//       }
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:37 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//       }
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//    {
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//    }
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//      valuePath       : 'identifier',
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +      },
Codacy found an issue: [Unexpected trailing comma.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//    }
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//      cellComponent   : 'ui-table/cell/admin/sales/cell-action'
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 12:49 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +//      name            : 'Action',
Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 13:01 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

2020-09-14 13:01 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +      //}
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 13:01 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +      //}
Codacy found an issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-14 13:01 UTC, niranjan94 commented on app/controllers/admin/sales/invoices.js
> +      //{
Codacy found an issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

2020-09-16 04:26 UTC, maze-runnar commented
what's next in this PR?

2020-09-21 11:04 UTC, mariobehling requested changes
Looks good to me, except for:
* Invoice # - I dont know where that number comes from, but I guess that can also be solved in another issue
* Dated - When looking at it it is unclear to me which date is meant (event date, invoice date, email sent date). We need to clarify this. The date should be "invoice date". Therefore please change "Dated" to "Invoice Date".

2020-09-21 12:46 UTC, maze-runnar commented
>  I guess that can also be solved in another issue

ok

2020-09-23 11:11 UTC, mariobehling commented
For invoice # please use:

2020-09-23 17:05 UTC, iamareebjamal commented
Invoice number will be handled in another PR so merging this

2020-09-23 17:06 UTC, merged