fix Tax information pop up in Wizard step 1 showing up towards bottom of screen
fossasia/open-event-frontend pull request #5368
Opened 2020-10-23 17:30 UTC by sachinchauhan2889

Fixes #4505 

#### Short description of what this resolves:
The issue with pop up tax information box is resolved. Now the pop up tax information modal is positioned well. The pop up is fully visible(not hidden by any other area). The session notify modal is placed at suitable placed. I have checked this modal from every scroll position and found result upto mark. Now position of session notify modal is perfect. 
Along with this, this PR also add "close" x icon on its top right of modal.

#### Changes proposed in this pull request:

- The issue with position of tax information modal is resolved.
- Add "close" x icon on its top right of modal.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

__screenshots__

_before_
![4505 before](https://user-images.githubusercontent.com/72552281/97034941-4526c580-1583-11eb-8bf9-f03be4fc70e9.png)

_after_
![4505 solved](https://user-images.githubusercontent.com/72552281/97034978-4e179700-1583-11eb-8a00-40f01a903eac.png)

2020-10-23 17:57 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562&bid=20732297)

2020-10-23 17:57 UTC, niranjan94 commented on app/components/modals/modal-base.js
> +      }
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562)

2020-10-23 17:57 UTC, niranjan94 commented on app/components/modals/modal-base.js
> +      if(this.noCropper) {
Codacy found an issue: [Expected space(s) after "if".](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562)

2020-10-23 18:41 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562&bid=20732297)

2020-10-23 18:41 UTC, niranjan94 commented on app/components/modals/modal-base.js
> +      }
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562)

2020-10-23 18:44 UTC, iamareebjamal commented
Why creating 2-3 PRs with same changes? Wait for a PR to be merged or solve all of these issues in the same PR

2020-10-23 18:45 UTC, niranjan94 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562&bid=20732297)

2020-10-23 18:45 UTC, niranjan94 commented on app/components/modals/modal-base.js
> +      }
Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392562)

2020-10-23 18:54 UTC, sachinchauhan2889 commented
> Why creating 2-3 PRs with same changes? Wait for a PR to be merged or solve all of these issues in the same PR

@iamareebjamal sorry, i am new to open source still understanding open source. i will take care of this.

2020-10-24 03:16 UTC, mariobehling requested changes
Thank you!

* [ ] Could you keep the overlay background semitransparent white, please for consistency?
* [ ] Please make the X button black (on white background).
* [ ] When a user closes the pop up using the X button and then clicks add tax information again nothing happens. Expected: It should open the pop up again.

2020-10-24 08:28 UTC, iamareebjamal commented
All 3 PR touch same file and make same changes and have same issues. To keep the conversation in one place where I have suggested changes.

2020-10-24 08:28 UTC, closed without merging

2020-10-24 08:29 UTC, iamareebjamal commented
See https://github.com/fossasia/open-event-frontend/pull/5367