enh: simplify sponsor box
fossasia/open-event-frontend pull request #5466
Opened 2020-11-03 05:43 UTC by maze-runnar

Fixes https://github.com/fossasia/open-event-frontend/issues/5462

![scrnli_11_3_2020_11-07-59 AM](https://user-images.githubusercontent.com/56407566/97953118-93c73180-1dc5-11eb-819c-3972f83f99f8.png)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-11-03 10:51 UTC, mariobehling requested changes
![Screenshot from 2020-11-03 11-46-56](https://user-images.githubusercontent.com/1583873/97976317-cd4e6b80-1dca-11eb-990a-5e892dfa2bf0.png)

* Please use the same spacing to the box edge for the "Edit" button as in other boxes
* Please decrease the space between previous/next button and the above table

2020-11-03 13:49 UTC, iamareebjamal commented on app/templates/components/events/view/overview/event-sponsors.hbs
> +<div class="content" style="width:94%;margin-left:3%;">
Why the need for inline styles?

2020-11-03 13:49 UTC, iamareebjamal commented on app/controllers/events/view/index.js
> +  // }
Delete the commented lines please

2020-11-04 16:15 UTC, iamareebjamal commented
@maze-runnar Please check the comments from @mariobehling and me about spacing and inline styles. Please try to reduce request review cycles

2020-11-04 16:16 UTC, iamareebjamal commented
I know it is for overriding CSS, but it shouldn't be needed

2020-11-06 21:11 UTC, iamareebjamal commented
Code looks good to me. Please resolve conflicts

2020-11-06 21:27 UTC, mariobehling commented
Let's try to standardize the design.

* Please make the table width the same width as the table in the above box.
* Please use the entire width of the table
   * expand the width of the sponsor names
   * move Type and Level to the right
* Reduce the space of the previous/next buttons to the above table

![Screenshot from 2020-11-06 22-19-11](https://user-images.githubusercontent.com/1583873/98416344-2f36fb80-207f-11eb-8f63-3998ce64b35e.png)

2020-11-07 11:00 UTC, mariobehling commented
I see the non-functional search box we already got rid of is back. It seems like you are working on different versions, cause I do not see it in your screenshot.

2020-11-07 11:30 UTC, maze-runnar commented
> * Please make the table width the same width as the table in the above box.

@iamareebjamal i have already used 15 wide column class, now for this I have to add `width` css.

2020-11-07 11:51 UTC, iamareebjamal commented
Go ahead

2020-11-07 12:29 UTC, maze-runnar commented
> Reduce the space of the previous/next buttons to the above table

@iamareebjamal  what about this? the space is kind of fix for every table.

2020-11-07 12:46 UTC, maze-runnar commented
- [ ] this is remaining to do.But it will change it in every place
![scrnli_11_7_2020_6-14-44 PM](https://user-images.githubusercontent.com/56407566/98441565-3284c280-2125-11eb-9461-a7aa1e766e11.png)

2020-11-07 21:24 UTC, iamareebjamal commented
Yes, reduce it for every table please

2020-11-08 06:04 UTC, iamareebjamal commented
Screenshot? Also I think the only thing which was needing change was pagination padding, what effect does changing table padding have in other sections of the site?

2020-11-08 08:41 UTC, maze-runnar commented
![scrnli_11_8_2020_2-09-55 PM](https://user-images.githubusercontent.com/56407566/98460637-1b4ce000-21cc-11eb-84b4-28abc92ea353.png)
![scrnli_11_8_2020_2-09-06 PM](https://user-images.githubusercontent.com/56407566/98460640-1ee06700-21cc-11eb-97a8-bd5d2db49316.png)

2020-11-10 12:19 UTC, mariobehling commented
According to your screenshots you are working with outdated code, which is confusing for me when I review it. So, I am updating the branch.

2020-11-10 12:25 UTC, mariobehling requested changes
There are few small issues. Maybe it is difficult for you to see it, but usually from a design perspective across all boxes the spacing of the heading and text should be the same. Below table spacing should be the same as the spacing of the heading. I tried to show it in my previous screenshot. I do not know how to make it clearer.

Could you also please do the following, please:
* Delete the column "Level" (sorry for the addition, but looking over it carefully, it does not really seem necessary here)
* Make the "Name" column wider. We have lots of space left on the right-hand side.
* Ensure the list really only shows the number of sponsors that are chosen: Here it shows "10", but 11 sponsors are shown in the box. There is an error somewhere.

![Screenshot from 2020-11-10 13-17-35](https://user-images.githubusercontent.com/1583873/98673800-2c2a5c80-2358-11eb-9065-2c2624bf747e.png)

2020-11-10 12:35 UTC, iamareebjamal commented
@mariobehling Are you talking about the space between the navigation panel and the end of the table? That is part of the table UI and independent of the sponsors section. The space was already reduced and can be reduced further, but it'll stay independent of the space above the table, and for example, look different in other parts of the UI. So, we can make it look equal here but then it'll make it look unequal in other parts of the UI wherever the table is used, so it's a question of trade-off and we can only use a constant spacing in the component.

About the 11 sponsors, that is another issue but can be taken in this as well, but it is not a UI change mentioned in the issue or something which broke due to these changes.

2020-11-10 13:33 UTC, mariobehling commented
@iamareebjamal I will file a separate issue later about standardization of design on dashboard. Thanks for taking in things that were not in the original issue! Appreciate it.

2020-11-18 17:32 UTC, iamareebjamal approved these changes

2020-11-18 17:33 UTC, merged