fix: Admin panel member since changed to date
fossasia/open-event-frontend pull request #5562
Opened 2020-11-10 17:20 UTC by codedsun

Fixes #5542  fix: Admin panel member since changed to date

#### Short description of what this resolves:

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-11-10 17:21 UTC, codedsun commented
@iamareebjamal - Review!

2020-11-10 18:18 UTC, mariobehling requested changes
Please change 24 hour format + AM/PM to 12 hour format + AM/PM

2020-11-10 22:59 UTC, iamareebjamal commented
Please use the format decided in #5533

2020-11-11 04:40 UTC, codedsun commented
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/20026440/98769139-1a9f8e00-2406-11eb-93b1-27940c6b907a.png">

Done @mariobehling @iamareebjamal

2020-11-11 04:45 UTC, iamareebjamal commented
Is that the format mentioned here? https://github.com/fossasia/open-event-frontend/pull/5533#pullrequestreview-526527704

2020-11-11 05:11 UTC, codedsun commented
@iamareebjamal - Now is it correct?

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/20026440/98771406-67856380-240a-11eb-830c-71715d523883.png">


Also IST should be harcoded?

2020-11-11 05:29 UTC, iamareebjamal commented
No need of IST

2020-11-11 05:29 UTC, iamareebjamal commented on open-event-frontend.iml
> +</module>
remove

2020-11-11 05:38 UTC, codedsun commented
Done @iamareebjamal

2020-11-11 06:59 UTC, mariobehling commented
No trailing 0 please. Use 7 Nov, instead of 07 Nov.

2020-11-11 07:00 UTC, mariobehling commented
Use 4:00 PM instead of 04:00 PM.

2020-11-11 08:27 UTC, codedsun commented
![Uploading image.png…]()

@mariobehling

2020-11-11 14:56 UTC, codedsun commented
@iamareebjamal Can this be merged?

2020-11-11 21:50 UTC, iamareebjamal approved these changes

2020-11-11 21:51 UTC, merged