fix: Country List in Forms show historic countries that do not exist today
fossasia/open-event-frontend pull request #5612
Opened 2020-11-13 16:20 UTC by sachinchauhan2889

Fixes #5604 

#### Short description of what this resolves:
remove all old countries.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2020-11-13 20:50 UTC, mariobehling commented on app/utils/dictionary/demography.ts
>      code : 'DD'
No longer in existence.

2020-11-13 20:51 UTC, mariobehling commented on app/utils/dictionary/demography.ts
> -  },
Please keep Hong Kong.

2020-11-13 20:52 UTC, mariobehling commented on app/utils/dictionary/demography.ts
> -  },
Taiwan is an existing territory even though China does not recognize it. Where did you get the info for that list? I am not an expert on all countries but it seems not all data is correct here.

2020-11-13 20:53 UTC, mariobehling commented on app/utils/dictionary/demography.ts
> -  },
Please check. I think it still exists.

2020-11-13 20:53 UTC, mariobehling commented on app/utils/dictionary/demography.ts
> -  },
Why no more Uganda?

2020-11-13 20:53 UTC, mariobehling commented on app/utils/dictionary/demography.ts
> -  },
still in existence

2020-11-13 20:55 UTC, mariobehling requested changes
These changes do not seem to be entirely correct. Please do more research about this information and also update if a country name or region name has changed. Also point to where you found the information. So we can understand it. Thanks.

2020-11-14 01:20 UTC, sachinchauhan2889 commented
> These changes do not seem to be entirely correct. Please do more research about this information and also update if a country name or region name has changed. Also point to where you found the information. So we can understand it. Thanks.

ok sir, i will check every country one by one

2020-11-15 21:30 UTC, MeghalBisht commented
> > These changes do not seem to be entirely correct. Please do more research about this information and also update if a country name or region name has changed. Also point to where you found the information. So we can understand it. Thanks.
> 
> ok sir, i will check every country one by one

Hey, are you still working on it?

2020-11-16 10:31 UTC, sachinchauhan2889 commented
> Hey, are you still working on it?

yes

2020-11-16 10:37 UTC, MeghalBisht reviewed
You can use this resource. It has all the countries recognized by the UN(2020).
https://www.worldometers.info/geography/countries-of-the-world/

2020-11-16 10:49 UTC, sachinchauhan2889 commented
> You can use this resource. It has all the countries recognized by the UN(2020).
> https://www.worldometers.info/geography/countries-of-the-world/

@MeghalBisht thanks.

2020-11-16 11:09 UTC, iamareebjamal commented
https://github.com/annexare/Countries/blob/master/dist/countries.json

2020-11-18 05:10 UTC, sachinchauhan2889 commented
> https://github.com/annexare/Countries/blob/master/dist/countries.json
> 
> ```js
> const countries = await (await fetch('https://raw.githubusercontent.com/annexare/Countries/master/dist/countries.json')).json()
> Object.entries(countries).map(([code, { name }]) => ({ code, name }))
> ```

2020-11-18 11:24 UTC, sachinchauhan2889 commented
> https://github.com/annexare/Countries/blob/master/dist/countries.json
> 
> ```js
> const countries = await (await fetch('https://raw.githubusercontent.com/annexare/Countries/master/dist/countries.json')).json()
> Object.entries(countries).map(([code, { name }]) => ({ code, name }))
> ```

@iamareebjamal sir, I tried this.
But _top level await_ is not working. 
getting error ---> _top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher._ 
I also used await in async function but error remain there.

Thats why I have totally matched counries in our demography,ts with your provided list. i have checked each and every country one by one and correct them and remove them.

2020-11-18 12:27 UTC, iamareebjamal commented
I meant run it in your browser console and copy it here, but you seemed to have done the same already

2020-11-18 12:40 UTC, sachinchauhan2889 commented
> I meant run it in your browser console and copy it here, but you seemed to have done the same already

@iamareebjamal  yes, sir.

2020-11-18 13:02 UTC, merged