Icon updated for "Ticket Buyer Information"
fossasia/open-event-frontend pull request #5625
Opened 2020-11-14 12:27 UTC by MeghalBisht

Fixes #5624 

#### Short description of what this resolves:
Icon changed for the "Ticket Buyer" information. 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

Attachments - 

![2020-11-14 (7)](https://user-images.githubusercontent.com/61330148/99146937-a03f6a00-26a2-11eb-8b01-f8dab329945a.png)

2020-11-14 12:49 UTC, sachinchauhan2889 requested changes
![Screenshot_20201114-181302](https://user-images.githubusercontent.com/72552281/99147286-cadef200-26a5-11eb-9476-78dc1a932c50.png)
 Add this icon on order form also.

2020-11-15 02:52 UTC, snitin315 requested changes
Need to rebase!

2020-11-15 02:52 UTC, snitin315 commented on app/templates/orders/pending.hbs
> +              @amount={{this.paymentAmount}}
Please revert these changes.

2020-11-15 11:27 UTC, Saumyachitransh01 reviewed
Use "money bill alternate outline icon".
This icon might look better.

2020-11-15 18:12 UTC, MeghalBisht commented
> Use "money bill alternate outline icon".
> It might look better.

It is being used in #5646

2020-11-15 18:17 UTC, Raunaksingh100 commented
> > Use "money bill alternate outline icon".
> > It might look better.
> 
> It is being used in #5646 

Ask the mentors for any suggestions

2020-11-15 18:18 UTC, Raunaksingh100 commented
> > Use "money bill alternate outline icon".
> > It might look better.
> 
> It is being used in #5646 

You can also use it doesn't matter 
The purpose of  your pr and my pr is different

2020-11-16 04:31 UTC, Saumyachitransh01 commented
> It is being used in #5646

Watch carefully, it's not the same

2020-11-19 09:42 UTC, mariobehling approved these changes
Looks good to me. Thank you!

2020-11-19 10:10 UTC, merged