fix:  Adjust first column and move date in new column in Organizers Attendees Overview Page
fossasia/open-event-frontend pull request #5672
Opened 2020-11-17 11:18 UTC by sachinchauhan2889

Fixes #5669 

#### Changes proposed in this pull request:
- from the first column take out the emails
- move "Date and Time" from first column to its own column
- create a column for "Date and Time" between ticket name and ticket price
- take out the xx days ago

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

__screenshots__

![g1](https://user-images.githubusercontent.com/72552281/99383901-98770400-28f4-11eb-9369-e568b58814cd.png)

2020-11-17 11:21 UTC, iamareebjamal commented on app/components/ui-table/cell/events/view/tickets/attendees/cell-time.js
> +export default class CellTime extends Component {}
No need of empty components in octane

2020-11-17 11:21 UTC, iamareebjamal commented on app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-time.hbs
> +{{#if (eq this.record.status 'completed')}}
`@record`

2020-11-18 00:33 UTC, daretobedifferent18 requested changes
fix the indentation of ```:``` in various places in list.hbs file

2020-11-18 02:09 UTC, iamareebjamal approved these changes

2020-11-18 02:09 UTC, merged