fix: without email speaker going to my-session
fossasia/open-event-frontend pull request #5751
Opened 2020-11-25 10:57 UTC by maze-runnar

Fixes #5342 
email is also required relation like track, so both needs to be make optional on server. That's why setting newSpeaker 'email' to " " .
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-11-25 11:35 UTC, iamareebjamal commented on app/controllers/events/view/sessions/create.js
> +        newSpeaker.set('email', " ");
null

2020-11-25 13:22 UTC, iamareebjamal commented
Is it working correctly?

2020-11-25 19:17 UTC, NaviRocker requested changes
Squash your Commits

2020-11-26 07:56 UTC, mariobehling commented
To ensure we understand the feature in the same way:
1. Email is always required for speakers filling in the call for speakers.
2. This can be overriden by the organizer, if they fill in a session submission themselves.

2020-11-26 08:02 UTC, maze-runnar commented
> This can be overriden by the organizer, if they fill in a session submission themselves.

Means organizer can set email to null?

2020-11-26 08:07 UTC, maze-runnar commented
server is giving 422 now:

```
{"errors": [{"status": 422, "source": {"pointer": "/data/attributes"}, "title": "Unprocessable Entity", "detail": "Missing required fields ['email']"}], "jsonapi": {"version": "1.0"}}
```

2020-11-26 08:59 UTC, iamareebjamal commented
Yes, only organizers can override email to null

2020-12-02 15:33 UTC, merged