Reasponsive Mobile event page
fossasia/open-event-frontend pull request #5757
Opened 2020-11-25 16:54 UTC by purnima143

Fixes #5666 

#### Short description of what this resolves:
I solved the mobile event page problem,i.e. Date,title and logo was not visible on mobile.

#### Changes proposed in this pull request:

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).

- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### Below is the screenshot of solved problem

![i2](https://user-images.githubusercontent.com/57852378/100258235-d3b8a900-2f6c-11eb-8660-ff9e62c930b8.PNG)
![i1](https://user-images.githubusercontent.com/57852378/100258239-d61b0300-2f6c-11eb-93c6-ec795d187ad9.PNG)
![i3](https://user-images.githubusercontent.com/57852378/100258242-d6b39980-2f6c-11eb-8e93-2d65ded7c718.PNG)

2020-11-25 19:15 UTC, NaviRocker requested changes
Please Squash your commits

2020-11-25 19:15 UTC, NaviRocker commented on app/styles/pages/public-event.scss
> +
No unwanted lines please.

2020-11-25 23:18 UTC, daretobedifferent18 reviewed
You have added a lot of code to make it responsive.
It can be done with min code changes. Pls, try it.

2020-12-05 13:19 UTC, daretobedifferent18 commented
@iamareebjamal Pls close this 
Fixed #5887

2020-12-05 13:20 UTC, closed without merging