Hide Profile
fossasia/open-event-frontend pull request #5819
Opened 2020-11-29 06:43 UTC by daretobedifferent18

Fixes #5817 

#### Short description of what this resolves:

#### Changes proposed in this pull request:

  - When session is expanded hide profile image, name, designation and org on the top area
  - Leave session info on top area as is
  - On the expanded area show position and organization below the speaker name without brackets

#### ScreenShots
![Screenshot from 2020-11-29 11-48-53](https://user-images.githubusercontent.com/71120226/100535143-2e3b5900-323c-11eb-87f8-2c5ae7aabbf9.png)
![Screenshot from 2020-11-29 11-49-26](https://user-images.githubusercontent.com/71120226/100535145-2f6c8600-323c-11eb-8076-00c4eaee9ad2.png)

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2020-11-29 06:54 UTC, daretobedifferent18 commented
@iamareebjamal It's Done.

2020-11-29 07:02 UTC, sachinchauhan2889 requested changes
microlocation and date-time information shift to left side after expanding session card. They must remain on right side even on expanding session.

2020-11-29 07:04 UTC, daretobedifferent18 commented
> microlocation and date-time information shift to left side after expanding session card. They must remain on right side even on expanding session.

That was actually a bug before which was not working but now its working correctly

2020-11-29 07:47 UTC, iamareebjamal commented
#5774 is not fixed

2020-11-29 07:50 UTC, daretobedifferent18 commented
> #5774 is not fixed

Working on both #5774 #5818 
See the Checklist in the description

2020-11-29 09:41 UTC, daretobedifferent18 commented
@iamareebjamal only left with #5818 but in this issue actually the link is been added in short Abstract and not in Slide url, so it will remain as it is, I think we can't change that.
Pls let me know what to do

2020-11-29 12:24 UTC, daretobedifferent18 commented
@iamareebjamal Done.

2020-11-29 12:30 UTC, mariobehling submitted a review, later dismissed
Nice work! Thanks

2020-11-29 13:45 UTC, iamareebjamal commented on app/components/public/session-item.hbs
> +                {{speaker.name}} {{#if (or speaker.position speaker.positionOrganisation)}}({{speaker.positionOrganisation}}){{/if}}
Simply use `if speaker.positionOrganisation`

2020-11-29 13:51 UTC, iamareebjamal commented on app/components/public/session-item.hbs
> +              {{t (if this.slidesUploaded 'Download Slides' 'Link to Slides')}}
t should have static string as argument. Please move if out and t in the conditions

2020-11-29 13:51 UTC, mariobehling commented
Oh, in the last iteration the date and time now appear twice.

Compare https://open-event-frontend-git-session-expanded-5817.eventyay.vercel.app/e/8fa7fd14/schedule

![Screenshot from 2020-11-29 14-50-54](https://user-images.githubusercontent.com/1583873/100543769-5e8df200-3252-11eb-9936-f05c7e79979a.png)

2020-11-29 13:51 UTC, iamareebjamal commented on app/components/public/session-item.hbs
> -            <iframe title="session-slides" class="slide-iframe mb-2" width="100%" frameborder="0" src="https://docs.google.com/gview?url={{ @session.slidesUrl }}&embedded=true"></iframe>
We want to show slides here. Please revert

2020-11-29 14:31 UTC, daretobedifferent18 commented
@iamareebjamal Made Changes

2020-11-29 15:47 UTC, iamareebjamal commented on app/components/public/session-item.hbs
> -            </a>
Don't remove this from here please

2020-11-29 16:05 UTC, daretobedifferent18 commented on app/components/public/session-item.hbs
> -            </a>
Done

2020-11-30 07:29 UTC, daretobedifferent18 commented
@iamareebjamal Pls review. This PR is completed

2020-11-30 07:39 UTC, iamareebjamal commented
@mariobehling I am merging this, but session collapsed will look very cluttered when there is both video stream and slides attached to it

2020-11-30 07:42 UTC, merged

2020-11-30 09:26 UTC, mariobehling commented
Yes, Thank you.

Let's talk about this in the weekly meeting.