typo changed
fossasia/open-event-frontend pull request #5848
Opened 2020-12-01 16:04 UTC by abhishekjha812

Fixes #

#### Short description of what this resolves:

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2020-12-01 16:51 UTC, vsasvipul0605 approved these changes

2020-12-01 18:48 UTC, sachinchauhan2889 requested changes
__not showing date and time.__

![add to calender](https://user-images.githubusercontent.com/72552281/100783073-5345ec80-3433-11eb-88e9-ce5aba1ad259.png)

2020-12-02 03:25 UTC, maze-runnar commented on app/components/public/add-to-calender.hbs
> +        {{general-date @event.startsAt 'date-time-long' tz=@event.timezone}} {{t 'to'}} {{general-date @event.endsAt 'date-time-long' tz=@event.timezone}}
that is not  a typo, it's format we have switched In a PR.

2020-12-02 12:27 UTC, daretobedifferent18 commented
@iamareebjamal Pls close this PR. Not needed

2020-12-02 14:01 UTC, closed without merging

2020-12-02 14:02 UTC, iamareebjamal commented
How come random people approve the most ridiculuous PRs and never review legitimate ones

2020-12-02 14:21 UTC, abhishekjha812 commented
> How come random people approve the most ridiculuous PRs and never review legitimate ones

sir! I am new to open source and i was just exploring , I had no intensions to disobey the open source ethics 
if you have any suggestions for me then please share it :)

2020-12-02 14:28 UTC, daretobedifferent18 commented
@abhishekjha812 Pls if you want to work on any issue, work on open issues and if you think there is an issue besides opened issues then pls first create a new issue.