changes to ticket download page
fossasia/open-event-frontend pull request #5856
Opened 2020-12-01 20:32 UTC by ksraj123

Fixes #5852 

#### Changes proposed in this pull request:

- Download Tickets button changes to All Tickets
- Icon for button changes to download icon

2020-12-01 22:11 UTC, mariobehling requested changes
There is a white space between the all tickets and invoice button now. Please keep the width of the button as it previously was. Thanks.

2020-12-02 03:37 UTC, Raunaksingh100 reviewed
Duplicate of #5860
I first say I am working on this issue so, why are  you spaming

2020-12-02 03:57 UTC, cggvuhh requested changes
there is lot of space and dupliacte of #5860 

 and #5860 already fixed the issue

2020-12-02 05:17 UTC, mariobehling commented
Please be friendly to each other and collaborate. As mentioned elsewhere if two people collaborate and contribute code to an issue together it would also count for both in a coding contest like Codeheat for example.

2020-12-02 05:59 UTC, ksraj123 commented
@Raunaksingh100 The pr you mentioned was opened around 7 hours after this one. So how could this be a duplicate or spam. Also this tone of communication should not be encouraged in open source. As I already said in the issue I did not see your comment when I started working on this. If the mentors feel that this is already fixed then please feel free to close this.

2020-12-02 05:59 UTC, ksraj123 commented
@mariobehling Does this look good now? I have made the spacing like it was before.

<img width="1201" alt="Screenshot 2020-12-02 at 11 25 28 AM" src="https://user-images.githubusercontent.com/39027928/100834270-9f277e80-3491-11eb-9b3b-f56db62eb22f.png">

2020-12-02 11:19 UTC, mariobehling approved these changes
Yes, looks good. Thank you!

Please keep the tone of the conversation positive and friendly. We are all here to learn as well.

2020-12-02 11:36 UTC, iamareebjamal commented on app/templates/orders/view.hbs
> +          <button class="ui labeled icon left floated seven wide column {{if this.isLoadingTickets 'loading'}} {{if this.device.isMobile 'fluid'}} button"
Please use flexbox with different style. Your solution is not responsive

2020-12-02 11:36 UTC, iamareebjamal requested changes
Please use flexbox as before

2020-12-02 13:32 UTC, ksraj123 commented
@iamareebjamal Unfortunately, I could not reproduce the responsiveness issues. Could you please share a screenshot for that.

Here is how it looked before on mobile devices -

<img width="1122" alt="original before changes" src="https://user-images.githubusercontent.com/39027928/100878565-5e9b2580-34d0-11eb-949b-cd05dbc3c34d.png">

Here is how it looks now -

<img width="1122" alt="Screenshot 2020-12-02 at 6 56 47 PM" src="https://user-images.githubusercontent.com/39027928/100878605-6a86e780-34d0-11eb-94e6-e4891a3f1f61.png">

Also, I think under the hood, semantic UI grid uses flexbox only.

<img width="322" alt="Screenshot 2020-12-02 at 7 01 06 PM" src="https://user-images.githubusercontent.com/39027928/100878889-c487ad00-34d0-11eb-8030-a69dd7453d4e.png">


Please share feedback and suggestions. Thanks

2020-12-02 13:47 UTC, iamareebjamal commented
> Could you please share a screenshot for that

You have done it above youself. See the difference carefully

2020-12-02 14:01 UTC, ksraj123 commented
Restored flexbox , now the space between the buttons not there on mobile if that was the resposivness issue we were talking about. Please have a look. Thanks

<img width="1353" alt="Screenshot 2020-12-02 at 7 25 32 PM" src="https://user-images.githubusercontent.com/39027928/100882078-c3f11580-34d4-11eb-97c9-cf0a6829a0e7.png">
<img width="834" alt="Screenshot 2020-12-02 at 7 25 57 PM" src="https://user-images.githubusercontent.com/39027928/100882091-c81d3300-34d4-11eb-8194-420d3cee0566.png">

2020-12-02 14:14 UTC, iamareebjamal commented
Not equal 
![image](https://user-images.githubusercontent.com/3874064/100883795-bf2d6100-34d6-11eb-9bcf-c26e1c5529e9.png)

Remove justify stretch and set flex: 1 to both elements

2020-12-02 14:23 UTC, ksraj123 commented
Oh, Thanks. Buttons made equal now.

<img width="448" alt="Screenshot 2020-12-02 at 7 51 02 PM" src="https://user-images.githubusercontent.com/39027928/100884872-036d3100-34d8-11eb-8551-8229716cfc50.png">

Should I squash my commits?

2020-12-02 15:41 UTC, iamareebjamal approved these changes

2020-12-02 15:42 UTC, merged

2020-12-02 15:43 UTC, iamareebjamal commented
Thanks for the contribution