Company field replaced with Organisation
fossasia/open-event-frontend pull request #5960
Opened 2020-12-08 11:24 UTC by Saumyachitransh01

Fixes #5854 

#### Short description of what this resolves:

Changed "Company" field to "Organisation" in Speaker and Attendee Form

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added necessary documentation (if appropriate)

2020-12-08 18:00 UTC, daretobedifferent18 submitted a review, later dismissed
Working fine for me

2020-12-10 03:45 UTC, maze-runnar approved these changes

2020-12-10 06:08 UTC, mariobehling commented
Existing events are still showing "company" in attendee form. Please resolve. Thank you.

![Screenshot from 2020-12-10 07-07-12](https://user-images.githubusercontent.com/1583873/101728304-82ed9800-3ab6-11eb-9cb0-38ba0f6773c9.png)

2020-12-10 06:51 UTC, Saumyachitransh01 commented
Done
![Screenshot from 2020-12-10 12-12-23](https://user-images.githubusercontent.com/55341933/101731772-23a57d00-3ae2-11eb-88e5-37519316ee0f.png)

2020-12-10 18:14 UTC, daretobedifferent18 requested changes
Pls change in validation rules ```company``` to ```organisation```
for eg. ```'Please enter your company'``` -> ```'Please enter your organisation'```

2020-12-11 10:56 UTC, iamareebjamal commented on app/mixins/custom-form.js
> +        fieldIdentifier : 'organisation',
Won't work. There is no field in server named organisation

2020-12-11 10:56 UTC, iamareebjamal commented on app/models/attendee.js
> +  organisation       : attr('string'),
Won't work

2020-12-11 10:56 UTC, iamareebjamal commented on app/models/custom-form.js
> +    organisation    : 'Organisation',
Won't work

2020-12-11 10:56 UTC, iamareebjamal commented on app/models/user.js
> +  organisation          : attr('string'),
Won't work

2020-12-11 11:09 UTC, daretobedifferent18 commented on app/mixins/custom-form.js
> +        fieldIdentifier : 'organisation',
@Saumyachitransh01 I have just asked you to changes messages places. Pls revert all the places where not required you did in last commit

2020-12-11 18:02 UTC, Saumyachitransh01 commented
This PR will implement for newly created events from now onwards. But for existing events. It needs server side migration.

2020-12-30 06:24 UTC, maze-runnar commented
@iamareebjamal for what the migration is actually needed in this PR? for alter_column?

2020-12-30 06:26 UTC, iamareebjamal commented
No, just change the name of custom form field of company to organizer.

2020-12-30 06:27 UTC, iamareebjamal commented
Change this in the open PR for custom form migration only

2020-12-31 03:24 UTC, iamareebjamal commented on app/components/forms/user-payment-info-form.js
> +    this.set('userBillingInfo', pick(this.authManager.currentUser, ['billingContactName', 'billingCity', 'billingPhone', 'organisation', 'billingTaxInfo', 'billingCountry', 'billingState', 'billingAd
```suggestion
    this.set('userBillingInfo', pick(this.authManager.currentUser, ['billingContactName', 'billingCity', 'billingPhone', 'company', 'billingTaxInfo', 'billingCountry', 'billingState', 'billingAddress', 'billingZipCode', 'billingAdditionalInfo']));
```

2020-12-31 03:24 UTC, iamareebjamal commented on app/components/forms/user-payment-info-form.js
> +          identifier : 'organisation',
```suggestion
        company: {
          identifier : 'company',
```

2020-12-31 03:34 UTC, merged