Front Page: Move Search Function to Top Bar
fossasia/open-event-frontend pull request #6007
Opened 2020-12-11 20:19 UTC by daretobedifferent18

Fixes #5927 

#### Short description of what this resolves:
Move the search feature to the top bar and substitute "Browse Events" with "Search Events"

#### Changes proposed in this pull request:
  - [ ] Implement the search in the place of "Browse Events"
  - [ ] Use a similar style and show "Search Events"
  - [ ] Expand the search box similar to GitHub when the user enters something
  - [ ] Delete the main search bar below the header
  - [ ] Show the top search bar on the same pages as Browse Events at the moments (do not change anything here)

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2020-12-12 01:06 UTC, mariobehling commented
Thank you. Please change the following:
* Switch search one position to the right
* Do not keep a straight line to the left
* Do not keep a border for the search box
* Add a search lens
* Expand search box length to the left when the user clicks into it

![Screenshot from 2020-12-12 01-40-57](https://user-images.githubusercontent.com/1583873/101968256-81d77a80-3c1e-11eb-88df-3615a0de2693.png)

2020-12-12 18:20 UTC, daretobedifferent18 commented
@mariobehling Pls have a look

2020-12-12 18:49 UTC, iamareebjamal commented
Please use #fafafa as bg color. Make default size of search bar smaller and don't expand it too much. GitHub expands it to show suggestions, we are not doing that currently.

2020-12-12 18:51 UTC, iamareebjamal commented
And it should also display and work on mobile

2020-12-12 22:05 UTC, iamareebjamal commented
Great, however I think mobile view should also contain the search bar in NavBar, or people won't notice it

2020-12-12 22:35 UTC, daretobedifferent18 commented
Then pls let me know where should I implement that. Bcz no space is in navbar

2020-12-12 23:10 UTC, iamareebjamal commented
![image](https://user-images.githubusercontent.com/3874064/101998892-4364bd00-3cfd-11eb-8ce9-521bd02beeba.png)

Lot of space

2020-12-12 23:11 UTC, iamareebjamal commented
If there is no space, do what eventbrite does

2020-12-13 07:45 UTC, mariobehling commented
Yes, please implement it in the top menu bar. Thanks

2020-12-13 08:04 UTC, mariobehling commented
Please also:
* Make the expanded version of the search box 20px longer
* Make the lens icon in the same color as the "Search Events" font
![Screenshot from 2020-12-13 08-47-37](https://user-images.githubusercontent.com/1583873/102006542-42925200-3d22-11eb-8965-eefccda8737a.png)

2020-12-13 18:26 UTC, daretobedifferent18 commented
@iamareebjamal Pls have a look

2020-12-13 23:26 UTC, iamareebjamal commented
Search icon still black. Can't click on cross till I type something

2020-12-14 05:33 UTC, daretobedifferent18 commented
> Search icon still black. Can't click on cross till I type something

cross icon is working for me

2020-12-14 15:08 UTC, daretobedifferent18 commented
@iamareebjamal I have made the changes and cross icon is working

2020-12-14 17:56 UTC, sachinchauhan2889 requested changes
look nice to me. 
only github actions / lint annotations needs to fix.

2020-12-14 17:59 UTC, daretobedifferent18 commented
> look nice to me.
> only github actions / lint annotations needs to fix.

lint is not giving any error

2020-12-14 18:55 UTC, iamareebjamal commented on app/components/nav-bar.js
> +    document.querySelector('#mobile-bar').classList.toggle('show-bar');
Why not using ember for this? Merging this as it has been too long, but please create a follow up PR to change DOM manipulation to ember

2020-12-14 18:55 UTC, iamareebjamal approved these changes

2020-12-14 18:56 UTC, merged

2020-12-14 18:56 UTC, iamareebjamal commented
Great job @daretobedifferent18 

Please follow up with a PR with minor change I mentioned

2020-12-14 18:59 UTC, daretobedifferent18 commented
@iamareebjamal also should I do #6017 with it bcz I think it will be easy to do it together bring search bar there as well

2020-12-14 19:01 UTC, iamareebjamal commented
Yes