Make links black
fossasia/open-event-frontend pull request #6058
Opened 2020-12-17 12:49 UTC by daretobedifferent18

Fixes #6056 

#### Short description of what this resolves:

#### Changes proposed in this pull request:

  - [ ] Place the link in a box, but do not make the box and button area use more space than the current implementation. Reason: It is clearer that the "Copy" button is related to the URL and that this is a unit if the URL is boxed. Furthermore the user can inspect the complete URL by moving back and forth in the box. If the user has to copy the URL first and enter it elsewhere it brings the attention away. Showcasing that we integrate video systems nicely in our system by visualizing the URL is a feature that we can show off to expert users. For normal users it does not disturb them neither as at the same time the URL does not take up too much space, because it is boxed.
  - [ ] Do not make the URL blue anymore to reduce focus on the link.
 - [ ] Change the color of the Copy button from black to gray to not have it stand out so much
  - [ ]  Behind the current "Copy" button add an arrow button as below that directs the user to the link

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2020-12-18 03:13 UTC, daretobedifferent18 commented
@mariobehling Pls could you explain me in detail 1 and 4 point of keeping url in box and implement arrow button behind the copy button.

Implementing arrow button behind the copy button will not show arrow button, couold you elaborate it.
Also making the url inside the box, should I also make them the links linkify after putting them inside the box.

2020-12-18 03:21 UTC, iamareebjamal commented
Add arrow button to the right of copy button

2020-12-18 04:51 UTC, mariobehling commented
> Also making the url inside the box, should I also make them the links linkify after putting them inside the box.

I think no need to linkify them. After the changes we can see how this works for a few days. Probably no more changes are needed after that.

2020-12-18 12:20 UTC, daretobedifferent18 commented
@iamareebjamal I am not getting arrow button with simantic icons

2020-12-18 16:41 UTC, Afzal-Ind commented
>I am not getting arrow button with simantic icons so I have used other icon. Pls have a look

Plz use share button as arrow button in semantic ui icon. Thanks.

2020-12-18 20:22 UTC, daretobedifferent18 commented
@iamareebjamal Done with this PR

2020-12-18 21:55 UTC, iamareebjamal commented
Field, copy button and link button are unaligned
![image](https://user-images.githubusercontent.com/3874064/102664894-c7112480-41a9-11eb-943f-ad31ef1d593c.png)

See this for comparison 
![image](https://user-images.githubusercontent.com/3874064/102664944-df813f00-41a9-11eb-9a38-136e5bd74faf.png)

2020-12-18 23:28 UTC, daretobedifferent18 commented
@iamareebjamal Done

2020-12-18 23:48 UTC, iamareebjamal commented
Still not aligned 
![Uploading image.png…]()

2020-12-19 00:08 UTC, daretobedifferent18 commented
> Still not aligned
> ![image](https://user-images.githubusercontent.com/3874064/102673329-b799d780-41b9-11eb-907f-ea7a3bcd8843.png)

aligned as in should I remove the space between two  buttons?
bcz dimensions of bith buttons are now same

2020-12-19 00:13 UTC, iamareebjamal commented
See the bottom line of the field and the copy button and compare

![image](https://user-images.githubusercontent.com/3874064/102673329-b799d780-41b9-11eb-907f-ea7a3bcd8843.png)

![image](https://user-images.githubusercontent.com/3874064/102664944-df813f00-41a9-11eb-9a38-136e5bd74faf.png)

2020-12-19 04:26 UTC, maze-runnar commented
it's overlapping with the room password. Please also fix that.
![Screenshot from 2020-12-19 09-54-26](https://user-images.githubusercontent.com/56407566/102680682-7cf76580-41e0-11eb-9ffc-f7c700fffedb.png)

2020-12-20 22:59 UTC, daretobedifferent18 commented
@iamareebjamal Pls have a look

2020-12-20 22:59 UTC, daretobedifferent18 commented
By mistake

2020-12-21 01:09 UTC, iamareebjamal commented
![Screenshot from 2020-12-21 06-32-30 (1)](https://user-images.githubusercontent.com/3874064/102729396-9c180380-4356-11eb-80f6-2b6981590ce2.png)

It's not taking up the width of the column

2020-12-21 02:29 UTC, daretobedifferent18 commented
> ![Screenshot from 2020-12-21 06-32-30 (1)](https://user-images.githubusercontent.com/3874064/102729396-9c180380-4356-11eb-80f6-2b6981590ce2.png)
> 
> It's not taking up the width of the column

Coul you suggest me the way out to deal with it bcz otherwise if I do then the table resp styling will be broken

2020-12-21 02:33 UTC, iamareebjamal commented
width: 100% on ui input

Also, instead of making icons 38 px, make ui input height 36px

2020-12-21 02:37 UTC, daretobedifferent18 commented
![Screenshot from 2020-12-21 08-07-48](https://user-images.githubusercontent.com/71120226/102733567-a12f7f80-4363-11eb-9b79-628abd7e39f9.png)

2020-12-21 02:39 UTC, daretobedifferent18 commented
@iamareebjamal Pls see the changes

2020-12-21 03:18 UTC, iamareebjamal commented
Dunno why but video source URL stays in its column but Join Video doesn't

![image](https://user-images.githubusercontent.com/3874064/102735726-2d907100-4369-11eb-98ed-74a74af8ea67.png)

This is not true for dev branch 
![image](https://user-images.githubusercontent.com/3874064/102735767-426d0480-4369-11eb-9261-8d04e372ab0b.png)

2020-12-21 03:28 UTC, daretobedifferent18 commented
> Dunno why but video source URL stays in its column but Join Video doesn't
> 
> ![image](https://user-images.githubusercontent.com/3874064/102735726-2d907100-4369-11eb-98ed-74a74af8ea67.png)
> 
> This is not true for dev branch
> ![image](https://user-images.githubusercontent.com/3874064/102735767-426d0480-4369-11eb-9261-8d04e372ab0b.png)

Exactly I don't know why this bug is getting. I checked into it but couldn't find anything relevent

2020-12-21 03:47 UTC, iamareebjamal commented
Move to other issues for now

2020-12-30 06:53 UTC, mariobehling commented
Updated branch, so I can test with latest changes.

2020-12-30 20:16 UTC, sachinchauhan2889 requested changes
@iamareebjamal sir, finally solved. I suggest changes. these changes solve issue. Please commit this suggested change in this PR. It takes huge time :yawning_face: .

2020-12-30 20:16 UTC, sachinchauhan2889 commented on app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
> +    <input class="truncate" type="text" value={{this.streamUrl}} placeholder={{this.streamUrl}} readonly>
```suggestion
    <input class="truncate" style="flex: 1 0 !important" type="text" value={{this.streamUrl}} placeholder={{this.streamUrl}} readonly>
```

2020-12-31 01:55 UTC, merged