fix: adding hcaptcha to register and forgot password
fossasia/open-event-frontend pull request #6087
Opened 2020-12-19 12:17 UTC by maze-runnar

Fixes https://github.com/fossasia/open-event-frontend/issues/6086

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-12-19 17:12 UTC, iamareebjamal requested changes

2020-12-19 17:12 UTC, iamareebjamal commented on config/environment.js
> +    sitekey : '4d94db5b-d3fd-407b-a574-e6ba0af9b73c',
Hard-coded key

2020-12-19 17:12 UTC, iamareebjamal commented
If key is not present, captcha shouldn't be enabled.

2020-12-19 17:19 UTC, maze-runnar commented
so key would be added by .env or from admin section?

2020-12-19 18:34 UTC, iamareebjamal commented
.env

2020-12-19 19:44 UTC, mariobehling commented
We have an area for a Google captcha in the admin section. Ultimately it would be good to have it here.

![Screenshot from 2020-12-19 20-43-54](https://user-images.githubusercontent.com/1583873/102698063-076cb300-423b-11eb-9a59-b5f441b5b3df.png)

2020-12-19 20:32 UTC, iamareebjamal commented
@mariobehling GSoC students just added it here for show without implementing it. We need the key at build time for the captcha service, just like the Google Maps API key, thus it is not possible to fetch it at runtime

2020-12-21 03:50 UTC, iamareebjamal commented on .env.example
> +HCAPTCHA_SITE_KEY=""
Move it to last and comment out

2020-12-21 03:51 UTC, iamareebjamal commented
Captcha shouldn't be enabled if key isn't present, as reviewed previously

2020-12-21 03:52 UTC, iamareebjamal commented on app/templates/components/forms/register-form.hbs
> +      <HCaptcha @onSuccess={{action 'captchaSuccess'}} @onExpired={{action 'onCaptchaExpired'}}/>
Simply use mut action instead of defining 2 actions in js

2020-12-21 04:54 UTC, maze-runnar commented
> Captcha shouldn't be enabled if key isn't present, as reviewed previously

ok

2020-12-21 06:59 UTC, iamareebjamal commented on app/components/forms/register-form.js
> +    return ENV.hcaptchaKey === null || ENV.hcaptchaKey === undefined ? false : true;
```suggestion
    return !!ENV.hcaptchaKey;
```

2020-12-21 07:00 UTC, iamareebjamal commented on app/components/forms/register-form.js
> +    return ENV.hcaptchaKey === null || ENV.hcaptchaKey === undefined ? false : true;
This doesn't change so no need of computed

2020-12-21 18:43 UTC, Jyotsna1006 commented on app/components/forms/register-form.js
> +  captcha   : false,
can i handle the issue?

2020-12-21 18:53 UTC, maze-runnar commented on app/components/forms/register-form.js
> +  captcha   : false,
what...?

2020-12-21 22:57 UTC, merged