fix: Mobile schedule menu
fossasia/open-event-frontend pull request #6163
Opened 2020-12-28 21:55 UTC by ranjitkshah

fixes #5919 

#### Short description of what this resolves:
enhancing the style of schedule sessions menu
![image](https://user-images.githubusercontent.com/61561415/103244991-b53b3880-4984-11eb-9666-c2ef23924532.png)

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2020-12-29 02:48 UTC, iamareebjamal commented on app/components/tables/utilities/search-box.js
> +    document.querySelector('#session-search').classList.toggle('show-div');
This is ember, not jquery

2020-12-29 08:41 UTC, sachinchauhan2889 requested changes
there are slight more changes needed. 
1) there must be an animation or transition when we focus in and focus out search box. You can compare search bar on top of front page.
2) On focus in, search bar expand from left side and sort box & timezone box disappear and search box takes its area.

You can refer this https://github.com/fossasia/open-event-frontend/pull/6007

![12111](https://user-images.githubusercontent.com/72552281/103271251-b51c5680-49df-11eb-90df-076d1f0ea236.png)
![2111](https://user-images.githubusercontent.com/72552281/103271245-b2216600-49df-11eb-8878-94a15e063bca.png)

2020-12-29 08:41 UTC, sachinchauhan2889 commented on app/templates/components/tables/utilities/search-box.hbs
> +  <Input  class="{{ if this.device.isMobile "expand-bar" "" }}" @type="text" @value={{readonly this.searchQuery}} @keyUp={{action 'setSearchQuery' value="target.value"}} onfocus={{ if this.device.isM
we are using this component at some other places also. At mobile view we don't want changes. exmaple:
![new speaker](https://user-images.githubusercontent.com/72552281/103270543-2d821800-49de-11eb-8f8e-f69104c7c188.png)

You can use this condition _(and this.device.isMobile (eq this.session.currentRoute 'public.sessions'))_

2020-12-29 10:09 UTC, iamareebjamal commented
No animation required

2020-12-29 22:15 UTC, ranjitkshah commented
Please review logic now @iamareebjamal

2020-12-31 03:13 UTC, maze-runnar commented
by time and drop dropdown going in 2nd line.

<img src="https://user-images.githubusercontent.com/56407566/103392420-d1390880-4b43-11eb-8262-0d47376e59e0.png" height="400px">

2020-12-31 19:37 UTC, ranjitkshah commented on app/components/widgets/time-zone-picker.hbs
> +  <div class="default text time-zone-picker-text">{{@timezone}}</div>
not able to add this.device.isMobile condition here. any help?

2020-12-31 19:39 UTC, ranjitkshah commented
updated screenshot:
![image](https://user-images.githubusercontent.com/61561415/103423692-fd00d080-4bcd-11eb-8635-4b62aaf70ef7.png)

2021-01-01 22:21 UTC, ranjitkshah commented
@maze-runnar pls review

2021-01-04 16:32 UTC, ranjitkshah commented
@iamareebjamal please re-review

2021-01-17 00:35 UTC, mariobehling commented
Expected is that the search bar covers the complete width. The search magnifying lense icon should stay at the same place.

2021-01-17 00:37 UTC, mariobehling commented
![Uploading Screenshot_20210117_013341_com.android.chrome.jpg…]()

2021-01-17 01:12 UTC, ranjitkshah commented
https://user-images.githubusercontent.com/61561415/104828365-ad3d2d00-588e-11eb-86a1-8695db24ab5c.mov

@mariobehling pls check now

2021-01-17 20:32 UTC, mariobehling commented
Thank you. The height of the search bar seems not to be the same height as the timezone box. Please check.

![Screenshot from 2021-01-17 21-30-50](https://user-images.githubusercontent.com/1583873/104855145-6c372e00-590b-11eb-95b4-222d5500b837.png)

2021-01-17 21:42 UTC, ranjitkshah commented
update : 
now both have same height 36px
![image](https://user-images.githubusercontent.com/61561415/104856857-c7cce000-593a-11eb-8d8b-bcf72971d38f.png)
![image](https://user-images.githubusercontent.com/61561415/104856874-da471980-593a-11eb-9f05-4970de5c32fc.png)

2021-01-21 19:35 UTC, ranjitkshah commented
> update :
> now both have same height 36px
> ![image](https://user-images.githubusercontent.com/61561415/104856857-c7cce000-593a-11eb-8d8b-bcf72971d38f.png)
> ![image](https://user-images.githubusercontent.com/61561415/104856874-da471980-593a-11eb-9f05-4970de5c32fc.png)

@mariobehling

2021-01-30 19:29 UTC, mariobehling submitted a review, later dismissed
Nice. Works on my tests. Thank you.

2021-01-30 20:30 UTC, iamareebjamal commented on app/components/tables/utilities/search-box.js
> +    this.sendAction('showSession');
Why?

2021-01-30 20:30 UTC, iamareebjamal commented
I don't understand the changes in this PR. Explain in the Tuesday meeting

2021-02-01 13:19 UTC, ranjitkshah commented
> I don't understand the changes in this PR. Explain in the Tuesday meeting

now, logic fixed  @iamareebjamal   And also I don't know why I was doing this ; )

2021-02-01 13:36 UTC, maze-runnar commented on app/components/widgets/time-zone-picker.hbs
> +  <div class="default text {{ if @device.isMobile "time-zone-picker-text" "" }}">{{@timezone}}</div>
```suggestion
  <div class="default text {{if @device.isMobile "time-zone-picker-text" "" }}">{{@timezone}}</div>
```

2021-02-01 13:36 UTC, maze-runnar commented on app/styles/libs/_helpers.scss
> +  max-width: 88px;
fix the sorting lint of scss. 
```suggestion
  max-width: 88px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
```

2021-02-01 13:36 UTC, maze-runnar commented on app/templates/components/tables/utilities/search-box.hbs
> +  <Input  class="{{ if (and this.device.isMobile (eq this.session.currentRouteName 'public.sessions')) "expand-bar" "" }}" @type="text" @value={{readonly this.searchQuery}} @keyUp={{action 'setSearch
```suggestion
  <Input  class="{{if (and this.device.isMobile (eq this.session.currentRouteName 'public.sessions')) "expand-bar" "" }}" @type="text" @value={{readonly this.searchQuery}} @keyUp={{action 'setSearchQuery' value="target.value"}} onfocus={{if (and this.device.isMobile (eq this.session.currentRouteName 'public.sessions')) (action @showSession)}} @focus-out={{if (and this.device.isMobile (eq this.session.currentRouteName 'public.sessions')) (action @showSession)}} placeholder="{{t "Search"}} ..." />
```

2021-05-14 15:57 UTC, MeghalBisht commented
A lot of changes were made for the schedule page after this PR was raised. Hence a lot of conflicts and redundant code is present. Hence closing this PR.
Also what I remember from the discussion with Areeb, he advised that too many changes were needed to achieve the result.
@ranjitkshah Please follow up in a new PR if needed.

2021-05-14 15:57 UTC, closed without merging