fix:enhance design of video-panel button
fossasia/open-event-frontend pull request #6236
Opened 2021-01-05 01:41 UTC by ranjitkshah

Fixes #6231 

#### Short description of what this resolves:
Screenshot:
![image](https://user-images.githubusercontent.com/61561415/103595827-76782600-4f22-11eb-9271-ab60ae89314f.png)

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-01-05 04:45 UTC, maze-runnar commented
> move the event name on the side panel itself a slight bit up

![Screenshot from 2021-01-05 10-15-18](https://user-images.githubusercontent.com/56407566/103607446-eeece000-4f3e-11eb-9a92-47b7221efa24.png)

2021-01-05 05:40 UTC, Creatoon commented on app/styles/components/stream.scss
> +  top: 3px;
you should write this is in rem in order to make it relative

2021-01-05 16:57 UTC, ranjitkshah commented
screenshot:
![image](https://user-images.githubusercontent.com/61561415/103674731-19718400-4fa5-11eb-9454-5ba0ecb27d7b.png)

2021-01-10 04:44 UTC, mariobehling requested changes
Thanks, please also change the following:
* center the < sign in the center of the icon when the panel is opened 
![Screenshot from 2021-01-10 05-42-11](https://user-images.githubusercontent.com/1583873/104114623-c3834000-5306-11eb-8167-1ad169d3ea35.png)
* Do not move up the event name heading as much. Leave more space above the event name (compare to sample screenshot in the issue itself)

2021-01-11 15:44 UTC, ranjitkshah commented
@mariobehling pls check now thanks

![image](https://user-images.githubusercontent.com/61561415/104203210-e4a47780-5451-11eb-8b83-1664a0d8236a.png)

2021-01-11 18:22 UTC, mariobehling approved these changes
Looks good to me. Thanks.

2021-01-11 18:59 UTC, merged