fix: Link speaker photo and speaker or session name to view page
fossasia/open-event-frontend pull request #6387
Opened 2021-01-15 16:45 UTC by afzal442

Fixes #6376 

#### Short description of what this resolves:

#### Changes proposed in this pull request:

- Added the links required
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-01-15 17:07 UTC, afzal442 commented
@Creatoon collaborate me where I m missing or linking issue

2021-01-15 19:51 UTC, sachinchauhan2889 requested changes
i don't think this issue is talking about directing to public page of event.

2021-01-16 03:11 UTC, afzal442 commented
Thanks. So where to link? Plz suggest.

2021-01-17 09:13 UTC, afzal442 commented
@sachinchauhan2889 @iamareebjamal plz review this. Thanks.

2021-01-20 14:21 UTC, afzal442 commented on app/templates/components/ui-table/cell/events/view/speakers/speaker-logo.hbs
> + <a class="image" href="{{href-to 'events.view.speaker.view'}}"><img alt="Speaker" class="ui middle aligned tiny circular image" src="{{if this.record this.record (if this.extraRecords.photoUrl this.
href didn't work.

2021-01-20 14:40 UTC, iamareebjamal commented
Do hit and trial on local machine, and make the PR WIP

2021-01-20 14:41 UTC, afzal442 commented
> Do hit and trial on local machine, and make the PR WIP

Alright Sir, I will. Thanks.

2021-01-24 14:57 UTC, closed without merging