fix: don't show links if field was empty
fossasia/open-event-frontend pull request #6556
Opened 2021-01-31 07:51 UTC by maze-runnar

Fixes https://github.com/fossasia/open-event-frontend/issues/6546

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-01-31 08:06 UTC, mariobehling approved these changes
The strange thing is, I cannot see this error appearing anymore on the live site. If this PR ensures the error does not re-appear even better.

2021-01-31 13:56 UTC, iamareebjamal requested changes

2021-01-31 13:56 UTC, iamareebjamal commented on app/templates/components/events/view/overview/speaker-view.hbs
> +                    {{#if (and (not-eq (get @speaker field.fieldIdentifier) 'https://github.com/') (not-eq (get @speaker field.fieldIdentifier) 'https://facebook.com/') (not-eq (get @speaker field.fi
Not good, why the links were being saved in the first place

2021-02-01 03:56 UTC, maze-runnar commented
now links will save correctly. And keeping `if` for previosly saved links.

2021-02-01 06:15 UTC, iamareebjamal commented
No, remove them. That's faulty logic. I'll manually make previous links null

Also, I have to think about why I added this && condition and the test so that it doesn't break anything

2021-02-01 08:16 UTC, maze-runnar commented
> No, remove them. That's faulty logic. I'll manually make previous links null

ok

2021-02-01 11:09 UTC, mariobehling commented
Yes, the issue is actually that these links exist in the first place. And they also show up on the public profile actually.

![Screenshot from 2021-02-01 12-08-04](https://user-images.githubusercontent.com/1583873/106451028-428f1280-6486-11eb-9dd8-5d355a68c68d.png)

2021-02-01 12:33 UTC, maze-runnar commented
> Yes, the issue is actually that these links exist in the first place. And they also show up on the public profile actually.
> 
> ![Screenshot from 2021-02-01 12-08-04](https://user-images.githubusercontent.com/1583873/106451028-428f1280-6486-11eb-9dd8-5d355a68c68d.png)

after this PR it would be resolved. as links would be save as null if they are not entered

2021-02-02 04:58 UTC, merged