right padding added to event side panel
fossasia/open-event-frontend pull request #6633
Opened 2021-02-07 13:43 UTC by astromanish

Fixes #6629 

#### Short description of what this resolves:

As padding added is a little greater than the width of a button so the content of the side panel never gets overlapped by the button.

![Screenshot (159)](https://user-images.githubusercontent.com/57687267/107148292-7089c080-6978-11eb-873f-122b7dd66063.png)

#### Changes proposed in this pull request:

- Right padding added to the side panel.

#### Checklist

- [ ✓ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ✓ ] My branch is up-to-date with the Upstream `development` branch.
- [ ✓ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ✓ ] I have added tests that prove my fix is effective or that my feature works
- [ ✓ ] I have added necessary documentation (if appropriate)

2021-02-07 14:54 UTC, rush-tea approved these changes

2021-02-07 14:55 UTC, rush-tea submitted a review, later dismissed

2021-02-10 06:49 UTC, mariobehling requested changes
This is not the right approach. It adds a spacing to the entire right side and hence the design does not appear centered anymore.

Expected. Only the text in the area of the minimize button should not overlap. All other text should stay in place.

2021-02-10 19:34 UTC, afzal442 commented
@astromanish the expected should be like this one as below
![c1](https://user-images.githubusercontent.com/11625672/107561736-e99d4800-6c04-11eb-8f1a-ed9862ef8b7a.JPG)
Plz do it as expected asap since it is a high priority issue.

2021-02-12 20:00 UTC, closed without merging

2021-02-12 20:01 UTC, astromanish commented
I sent another pull request for this issue so closing this pull request.