Added Honor Line For Areeb Sir
fossasia/open-event-frontend pull request #7215
Opened 2021-05-01 00:13 UTC by Creatoon

#7202 

#### Short description of what this resolves:
Tribute To Areeb Sir Please Merge This PR.

![Screenshot_2021-05-01 Open Event](https://user-images.githubusercontent.com/65965202/116764843-16147380-aa40-11eb-88e2-73f05f4930b4.png)

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-05-01 16:44 UTC, Creatoon commented
@mariobehling sir please merge this PR, very thankful to you.

2021-05-05 10:58 UTC, sachinchauhan2889 approved these changes

2021-05-05 13:20 UTC, mariobehling requested changes
Please change it as follows:
- [x] Move text in front of "Copyright" and use the same font and size as the text here. Show it in the same line to the left of Copyright.
- [x] Change "Copyright © 2021 eventyay" to "© 2021 eventyay"

2021-05-06 09:35 UTC, Creatoon commented
@mariobehling @sachinchauhan2889  After Changes

![Screenshot_2021-05-06 eventyay](https://user-images.githubusercontent.com/65965202/117276380-778f7480-ae7c-11eb-88af-bd36cdf2c497.png)

2021-05-06 15:24 UTC, MeghalBisht commented on app/templates/components/footer-main.hbs
> +          <span class="item">Made with <i class="red heart icon"></i> By- Areeb Jamal & Team</span>
Please wrap in t

2021-05-07 00:27 UTC, MeghalBisht commented on app/templates/components/footer-main.hbs
> +          <span class="item">{{t 'Made with'}} <i class="red heart icon"></i> {{t 'By- Areeb Jamal'}} &amp; {{t 'Team'}}</span>
Name cannot be translated

2021-05-07 00:29 UTC, Creatoon commented on app/templates/components/footer-main.hbs
> +          <span class="item">{{t 'Made with'}} <i class="red heart icon"></i> {{t 'By- Areeb Jamal'}} &amp; {{t 'Team'}}</span>
ok

2021-05-08 13:35 UTC, sachinchauhan2889 approved these changes

2021-05-14 15:48 UTC, mariobehling commented
Please change the heart to the same color as the text.

2021-05-15 14:30 UTC, MeghalBisht commented on app/templates/components/footer-main.hbs
> +          <span class="item">{{t 'Made with'}} <i class="heart icon"></i> {{t 'By'}}- Areeb Jamal &amp; {{t 'Team'}}</span>
We can just add "Maintained by" instead of "made with heart"

2021-05-15 19:04 UTC, MeghalBisht submitted a review, later dismissed

2021-05-16 05:10 UTC, ranjitkshah approved these changes

2021-06-03 07:27 UTC, merged