feat: Implement video tab on/off switch similar to wizard switches and show pop-up
fossasia/open-event-frontend pull request #7428
Opened 2021-06-10 22:19 UTC by ranjitkshah

Fixes #6416 

#### Short description of what this resolves:
https://www.loom.com/share/34446dfb79764177a6d5e028bf951007

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-06-10 23:05 UTC, iamdevvalecha approved these changes
NICE! LGTM

2021-06-11 21:45 UTC, ranjitkshah commented
We can access video rooms (even if feature is disabled) by going directly to something like `http://localhost:4200/e/b6ac502f?side_panel=true`
We need to hide video rooms from the side panel as well.
What if chat is also disabled then side panel would be empty, should it be disabled as well?
@mariobehling What do you suggest?

2021-06-28 10:19 UTC, maze-runnar commented
just resolve conflict for now, and it's good to go. For above issue you mentioned, we will see later.

2021-06-30 08:58 UTC, maze-runnar commented on app/templates/events/view/videoroom/list.hbs
> +  @actionName={{if this.model.event.isVideoroomEnabled 'switches it off. "Continue using video rooms.' 'Yes - activate video rooms now. I agree to pay the fees.'}}
```suggestion
  @actionName={{if this.model.event.isVideoroomEnabled 'switches it off. Continue using video rooms.' 'Yes - activate video rooms now. I agree to pay the fees.'}}
```

2021-06-30 09:07 UTC, maze-runnar approved these changes

2021-07-01 14:36 UTC, mariobehling commented
Please take out the pop-up as we are currently not able to add the payment feature for this part.

2021-07-05 13:20 UTC, sachinchauhan2889 requested changes
By default isVideoEnabled is false.
This means for existing events also isVideoEnabled is also false. This means we will not see join button on existing events. Organizer will need to go to video section to enable videoroom.

2021-07-06 05:40 UTC, ranjitkshah commented
> By default isVideoEnabled is false.
> This means for existing events also isVideoEnabled is also false. This means we will not see join button on existing events. Organizer will need to go to video section to enable videoroom.

we will do that manually on prod db for all events. If I create new migrations it will reflect conflicts with previous migration.

2021-07-06 14:07 UTC, sachinchauhan2889 approved these changes
LGTM after manually migration.

2021-07-08 01:02 UTC, MeghalBisht approved these changes

2021-07-08 01:36 UTC, merged