feat: update payment status
fossasia/open-event-frontend pull request #7561
Opened 2021-07-15 00:44 UTC by maze-runnar

Fixes https://github.com/fossasia/open-event-frontend/issues/7540

required https://github.com/fossasia/open-event-server/pull/8102

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-07-16 07:42 UTC, mariobehling requested changes
As discussed in meeting:
1. Please add filters to organizer view
2. Add status info on invoice page. It should not show "Paid" if the user has not paid, e.g. it is possible that the admin of the systems sets a status to resolved for an event that has not paid anything.

2021-07-16 08:55 UTC, maze-runnar commented
![Screenshot from 2021-07-16 14-25-16](https://user-images.githubusercontent.com/56407566/125921475-a6dedf46-9fb3-48f1-9a7c-946b946b01d8.png)
![Screenshot from 2021-07-16 14-25-12](https://user-images.githubusercontent.com/56407566/125921486-ae084873-85d4-4e9f-b5f6-bb936ab23c90.png)

2021-07-17 07:25 UTC, mariobehling commented
Looks good. Thank you.

2021-07-20 11:23 UTC, mariobehling approved these changes

2021-07-20 11:41 UTC, merged