fix: arrange sales in arranging order
fossasia/open-event-frontend pull request #7567
Opened 2021-07-15 16:38 UTC by maze-runnar

Fixes simplify sales page subpart
![Screenshot from 2021-07-15 22-07-12](https://user-images.githubusercontent.com/56407566/125825172-8b0f1341-db98-4737-bf2e-1ef49f35a742.png)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-07-16 07:40 UTC, mariobehling requested changes
Please change: The newest dates should be on top. Older dates on the bottom.

2021-07-16 08:59 UTC, maze-runnar commented
![Uploading Screenshot from 2021-07-16 14-29-16.png…]()

2021-07-16 14:03 UTC, MeghalBisht approved these changes

2021-07-17 07:23 UTC, mariobehling approved these changes

2021-07-17 07:23 UTC, merged