Moved search field to top on search pages #7587
fossasia/open-event-frontend pull request #7635
Opened 2021-08-01 12:24 UTC by ayushcse042

Fixes #7587

#### Short description of what this resolves:
Moved enter event name search field to top on search pages

#### Changes proposed in this pull request:

-side-bar.hbs
-nav-bar.hbs
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-08-01 12:27 UTC, ayushcse042 commented
![previous](https://user-images.githubusercontent.com/72243090/127770783-04eb7964-8646-477f-a73b-3a65bb57d799.png)
![updated](https://user-images.githubusercontent.com/72243090/127770785-4f39a38d-9d73-4f54-ba25-ba4d02817285.png)

changes I have made on Explore page.
Shifted the enter event name search field to top on search pages.

2021-08-01 17:50 UTC, NaviRocker approved these changes
Good Job

2021-08-02 11:05 UTC, pc-beast requested changes
Search Bar is not working now.

2021-08-02 16:35 UTC, maze-runnar commented
@ayushcse042 please test the changes on your local.

2021-08-03 01:43 UTC, maze-runnar commented
@sachinchauhan2889 is handling this in pr https://github.com/fossasia/open-event-frontend/pull/7621

2021-08-03 01:43 UTC, closed without merging