fix: changed registeredComany to organization
fossasia/open-event-frontend pull request #7888
Opened 2021-10-05 18:33 UTC by akshitarora921

Fixes #7883 

#### Short description of what this resolves:
The order company information box shows the "Name" instead of "Organisation" in the left column of the box. Please correct this and show "Organisation" in all company boxes in the order process and final order page.

#### Changes proposed in this pull request:
change variable from registered company to organization
-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2021-10-05 18:44 UTC, iamdevvalecha requested changes
wrong

2021-10-05 18:46 UTC, iamdevvalecha commented
you just need to change in the box  from name to Organisation.
![Screenshot from 2021-10-06 00-10-04](https://user-images.githubusercontent.com/71969867/136083995-236f340e-b583-4ac5-ac3c-523fc3b38cab.png)

2021-10-05 19:33 UTC, iamdevvalecha approved these changes
LGTM!

2021-10-05 19:38 UTC, akshitarora921 commented
@iamdevvalecha  Please add hacktoberfest-accepted label.

2021-10-05 22:50 UTC, mariobehling approved these changes

2021-10-05 22:50 UTC, merged

2021-10-06 06:03 UTC, akshitarora921 commented
@iamdevvalecha @mariobehling Please add hacktoberfest-accepted label.