fix: able to follow group on event page
fossasia/open-event-frontend pull request #8112
Opened 2021-11-18 05:46 UTC by pc-beast

Fixes #8091 

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-11-18 06:03 UTC, progmatic-99 requested changes

2021-11-18 06:03 UTC, progmatic-99 commented on app/controllers/public.js
> +    return !!this.follower;
Why not write `this.follower` ??

2021-11-18 06:57 UTC, pc-beast commented on app/controllers/public.js
> +    return !!this.follower;
we want the boolean output from here

2021-11-23 09:17 UTC, mariobehling commented
Not able to follow group on test deployment. "Unexpected Error"

Compare https://open-event-frontend-git-fork-pc-beast-i8091-eventyay.vercel.app/g/108

![Screenshot from 2021-11-23 10-15-07](https://user-images.githubusercontent.com/1583873/142997981-bd38135d-af59-4448-8b24-e01fbd668526.png)

2021-11-25 05:15 UTC, pc-beast commented
> Not able to follow group on test deployment. "Unexpected Error"
> 
> Compare https://open-event-frontend-git-fork-pc-beast-i8091-eventyay.vercel.app/g/108
> 
> ![Screenshot from 2021-11-23 10-15-07](https://user-images.githubusercontent.com/1583873/142997981-bd38135d-af59-4448-8b24-e01fbd668526.png)

Opened #8135 as it is unrelated to changes in this PR. This can be merged @mariobehling.

2021-11-25 15:17 UTC, progmatic-99 approved these changes
This can be merged. @mariobehling

2021-11-25 15:42 UTC, merged