fix: indentation & link session & speakers page to organizer area
fossasia/open-event-frontend pull request #8251
Opened 2022-01-10 11:34 UTC by progmatic-99

Fixes #8250 
![Screenshot 2022-01-10 at 16-59-11 progmatic 99 attendee-tickets Events eventyay](https://user-images.githubusercontent.com/42090582/148759573-4f7ffab3-9ff1-4774-9b5d-81ba103b57df.png)

2022-01-10 14:57 UTC, mariobehling requested changes
If the speaker has several sessions the sessions do not show up in the correct place.

![Screenshot from 2022-01-10 15-55-29](https://user-images.githubusercontent.com/1583873/148786622-1d337795-ed54-42f5-8fac-cebee1ffe42f.png)

2022-01-10 17:33 UTC, progmatic-99 commented
@mariobehling 

![Screenshot 2022-01-10 at 22-58-58 progmatic 99 attendee-tickets Events eventyay](https://user-images.githubusercontent.com/42090582/148811616-71555365-e5c4-4abc-ad3d-e5b7aa223216.png)

2022-01-10 17:38 UTC, mariobehling approved these changes

2022-01-12 14:56 UTC, merged

2022-01-17 17:34 UTC, mariobehling commented
Unfortunately this does not work as expected in the end. Therefore I reopened the issue:

The session pages that can be viewed by the organizers link to the "private speakers CfS" page (e.g. https://eventyay.com/e/6b901f56/cfs/speaker/5983). They should be linking to the speakers pages that can be viewed by the organizer (e.g. https://eventyay.com/events/6b901f56/speaker/5983)