Enhancement/schedule page/time and search occupied
fossasia/open-event-frontend pull request #8893
Opened 2023-07-01 06:52 UTC by blackmouse572

Resolves  #8757 Reduce area occupied by time and search field on schedule page

#### Short description of what this resolves:
- Change Seach box behaviour
- Search and time occupied 1 instead of 2 rows

#### Changes proposed in this pull request:

- Search Box Input which will take whole area to shorter version of it. When use focus, it will expand to original.
- Search Box and Timezone place in 1 row on mobile screen instead of 2. These components is space between each others

**BEFORE**
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/51663402-3635-42b0-b5e7-c77dadd0a6b0)

**AFTER**
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/05558cd7-d78b-4073-972c-73e062e1234d)

-- On Click
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/498907f2-4ef7-4ba0-bde1-1fa8ac71772c)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-07-03 10:45 UTC, mariobehling commented
Thank you. Nice work. Please see comments below.

1. On your screenshot it is already visible that the height of the mobile time and search boxes is different. The time box and search box should have the same height and there should be a space between them.
2. The search box should expand over the time box when clicked.
Current PR
![Screenshot from 2023-07-03 12-40-51](https://github.com/fossasia/open-event-frontend/assets/1583873/d6b0f56c-e621-4ee5-b3a6-09bf903e85c7)

Intended view
![Screenshot from 2023-07-03 12-40-51a](https://github.com/fossasia/open-event-frontend/assets/1583873/f563f77c-1e89-479b-9e9b-33b812b4c664)

Compare the idea of an expanding search box here for example https://codepen.io/k185/pen/PQajXE

2023-07-04 13:15 UTC, cweitat requested changes
https://github.com/fossasia/open-event-frontend/pull/8893#issuecomment-1617901591

2023-07-08 09:28 UTC, blackmouse572 commented
> Thank you. Nice work. Please see comments below.
> 
> 1. On your screenshot it is already visible that the height of the mobile time and search boxes is different. The time box and search box should have the same height and there should be a space between them.
> 2. The search box should expand over the time box when clicked.
>    Current PR
>    ![Screenshot from 2023-07-03 12-40-51](https://user-images.githubusercontent.com/1583873/250534339-d6b0f56c-e621-4ee5-b3a6-09bf903e85c7.png)
> 
> Intended view ![Screenshot from 2023-07-03 12-40-51a](https://user-images.githubusercontent.com/1583873/250534337-f563f77c-1e89-479b-9e9b-33b812b4c664.png)
> 
> Compare the idea of an expanding search box here for example https://codepen.io/k185/pen/PQajXE
> 
> Test at https://eventyay.com/e/7cfe0771/schedule and https://open-event-frontend-git-fork-blackmouse572-enha-54d351-eventyay.vercel.app/e/7cfe0771/schedule

I have change based on the reply. this is the newest version. 
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/90d0d390-05f5-4df9-97f0-6c509a22185d)

- I have change from default SearchBox into conditional render. Whether it is mobile device to implement the custom scss expand search box. This maybe cause the boilerplate but it easy to maintain and modified.

2023-07-08 09:34 UTC, cweitat commented
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/f03b8aa6-ed46-4a6b-a04c-4924185830ff)
@blackmouse572 uneven height

2023-07-08 13:06 UTC, cweitat requested changes

2023-07-08 13:06 UTC, cweitat commented on app/styles/libs/_helpers.scss
> +
do not include unnecessary line breaks

2023-07-08 13:06 UTC, cweitat commented on app/styles/libs/_helpers.scss
> +
same for this and rest

2023-07-08 13:06 UTC, cweitat commented on app/styles/pages/public-session.scss
> +    width: 100%;
Github Lint

2023-07-08 13:06 UTC, cweitat commented on app/styles/pages/public-session.scss
> +    .search-box {
and the rest

2023-07-08 13:08 UTC, cweitat commented
Please include new screenshot of latest update

2023-07-10 08:04 UTC, blackmouse572 commented
--EMPTY STATE
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/b2a63c56-93d1-4f7b-9a64-54917c13866f)
--FOCUS STATE
![image](https://github.com/fossasia/open-event-frontend/assets/77144199/ae34c1a8-c946-4d4b-a158-6fab14143ad1)

2023-07-10 13:54 UTC, cweitat requested changes
uncompliance of formatting

2023-07-10 15:40 UTC, cweitat commented
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/88b30c0f-2d63-4c65-bca9-7b5e95eebde3)

2023-07-10 15:41 UTC, cweitat commented
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/88b30c0f-2d63-4c65-bca9-7b5e95eebde3)

2023-07-19 15:42 UTC, blackmouse572 commented
Sorry for the late, just fix the scss break point to display gap on mobile device, also move the `transition` to input selector for the animation.

2023-07-24 05:31 UTC, cweitat commented
@blackmouse572 is this considered as fixed? do fix your codacy too

2023-07-24 05:58 UTC, blackmouse572 commented
> @blackmouse572 is this considered as fixed? do fix your codacy too

Yes, really sorry for my latency, I am working on it. Secondly, I notice from the tablet screen, the gap is not apply, so i change the breakpoint to suitable value so that when the search and timezone apply same row, the gap is applied to. That why i consider a fix. If any problem please let me know. Thank you for you time <3

2023-08-21 03:51 UTC, closed without merging

2023-08-21 03:51 UTC, mariobehling commented
Thank you for your contribution. I am closing this PR as it has been solved in the meantime.