feature-8866: Rename form with meaningful name in order form
fossasia/open-event-frontend pull request #8903
Opened 2023-07-03 02:28 UTC by lthanhhieu

Fixes #8866 

#### Short description of what this resolves:
- Rename form with meaningful name in order form

#### Changes proposed in this pull request:
- Rename form with meaningful name in order form

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-07-03 09:31 UTC, khangon commented
Hi @cweitat , @norbusan 
We have renamed two languages variable names.
Please help me check.
![image](https://github.com/fossasia/open-event-frontend/assets/135116292/4ed389e4-cf27-43db-b3e5-874acd9804b6)

2023-07-04 13:07 UTC, cweitat approved these changes

2023-07-04 13:14 UTC, cweitat requested changes
Please resolve conflicts. Thank you

2023-07-06 13:59 UTC, lthanhhieu commented
> Please resolve conflicts. Thank you

Hi @cweitat

I fixed it. Please help me to check and review it.

Thanks

2023-07-06 14:46 UTC, cweitat approved these changes

2023-07-06 15:03 UTC, merged